import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoCRMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'amoCRM Токен',
                'verbose_name_plural': 'amoCRM Токены',
            },
        ),
        migrations.CreateModel(
            name='FeatureIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.FileField(upload_to='features/icons/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Контент - Иконка',
                'verbose_name_plural': 'Контент - Иконки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название модели')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название модели')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название модели')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название модели')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='Главное изображение')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='products/cards/', verbose_name='Изображение для карточки')),
                ('slider_image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 420x210px. Если не указано, используется main_image', null=True, upload_to='products/slider/', verbose_name='Изображение для слайдера')),
                ('slider_year', models.CharField(default='2025', help_text='Отображается в слайдере', max_length=4, verbose_name='Год для слайдера')),
                ('slider_price', models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера')),
                ('slider_price_uz', models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера')),
                ('slider_price_ru', models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера')),
                ('slider_price_en', models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера')),
                ('slider_power', models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера')),
                ('slider_power_uz', models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера')),
                ('slider_power_ru', models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера')),
                ('slider_power_en', models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера')),
                ('slider_fuel_consumption', models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера')),
                ('slider_fuel_consumption_uz', models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера')),
                ('slider_fuel_consumption_ru', models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера')),
                ('slider_fuel_consumption_en', models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера')),
                ('slider_order', models.PositiveIntegerField(default=0, help_text='Чем больше число, тем раньше появится в слайдере', verbose_name='Порядок в слайдере')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, help_text='Продукт будет добавлен в главный слайдер', verbose_name='Показывать на главной')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контент - Автомобиль',
                'verbose_name_plural': 'Контент - Автомобили',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('hero_image', models.ImageField(blank=True, help_text='Изображение для страницы категории', null=True, upload_to='categories/heroes/', verbose_name='Фоновое изображение')),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контент - Марка',
                'verbose_name_plural': 'Контент - Марка автомобиля',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('short_description_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('short_description_ru', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('short_description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('contact_info', models.TextField(default='Присылайте резюме на info@autoliga.uz', verbose_name='Контакты')),
                ('contact_info_uz', models.TextField(default='Присылайте резюме на info@autoliga.uz', null=True, verbose_name='Контакты')),
                ('contact_info_ru', models.TextField(default='Присылайте резюме на info@autoliga.uz', null=True, verbose_name='Контакты')),
                ('contact_info_en', models.TextField(default='Присылайте резюме на info@autoliga.uz', null=True, verbose_name='Контакты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вакансии - Вакансия',
                'verbose_name_plural': 'Вакансии - Вакансии',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('region', models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Fargʻona viloyati', 'Fargʻona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Qoraqalpogʻiston Respublikasi', 'Qoraqalpogʻiston Respublikasi')], max_length=100, verbose_name='Регион')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('product', models.CharField(blank=True, help_text='Какую модель автомобиля интересует клиента', max_length=200, null=True, verbose_name='Модель техники')),
                ('referer', models.URLField(blank=True, help_text='URL страницы, с которой отправлена заявка', max_length=500, null=True, verbose_name='Referer (откуда пришёл)')),
                ('utm_data', models.TextField(blank=True, help_text='UTM метки в JSON формате', null=True, verbose_name='UTM метки')),
                ('visitor_uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='amoCRM Visitor UID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('message', models.TextField(blank=True, default='', verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('done', 'Обработана')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('amocrm_status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Успешно отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='pending', help_text='Статус отправки в amoCRM', max_length=20, verbose_name='Статус amoCRM')),
                ('amocrm_lead_id', models.CharField(blank=True, help_text='ID лида после успешной отправки', max_length=50, null=True, verbose_name='ID лида в amoCRM')),
                ('amocrm_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в amoCRM')),
                ('amocrm_error', models.TextField(blank=True, help_text='Текст последней ошибки при отправке', null=True, verbose_name='Ошибка amoCRM')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uz_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заявки - Общая заявка',
                'verbose_name_plural': 'Заявки - Общие заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('desc', models.TextField(help_text='Отображается в превью новости', max_length=200, verbose_name='Краткое описание для карточки')),
                ('desc_uz', models.TextField(help_text='Отображается в превью новости', max_length=200, null=True, verbose_name='Краткое описание для карточки')),
                ('desc_ru', models.TextField(help_text='Отображается в превью новости', max_length=200, null=True, verbose_name='Краткое описание для карточки')),
                ('desc_en', models.TextField(help_text='Отображается в превью новости', max_length=200, null=True, verbose_name='Краткое описание для карточки')),
                ('slug', models.SlugField(blank=True, help_text='Генерируется автоматически из заголовка', max_length=255, unique=True, verbose_name='URL')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Фото автора')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='news/previews/', verbose_name='Главное фото')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать новость на сайте', verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем больше число, тем выше в списке', verbose_name='Порядок')),
                ('created_at', models.DateField(help_text='Введите дату публикации вручную', verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': ' - Новость',
                'verbose_name_plural': 'Контент - Новости',
                'ordering': ['-order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('youtube', 'YouTube видео'), ('video', 'Видео файл')], max_length=10, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, help_text='Заголовок H3 перед текстовым блоком', max_length=500, null=True, verbose_name='Заголовок (необязательно)')),
                ('title_uz', models.CharField(blank=True, help_text='Заголовок H3 перед текстовым блоком', max_length=500, null=True, verbose_name='Заголовок (необязательно)')),
                ('title_ru', models.CharField(blank=True, help_text='Заголовок H3 перед текстовым блоком', max_length=500, null=True, verbose_name='Заголовок (необязательно)')),
                ('title_en', models.CharField(blank=True, help_text='Заголовок H3 перед текстовым блоком', max_length=500, null=True, verbose_name='Заголовок (необязательно)')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Фото')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube ссылка')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='news/videos/', verbose_name='Видео файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Блок новости',
                'verbose_name_plural': 'Блоки новостей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('value_uz', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.featureicon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_specs', to='main.product')),
            ],
            options={
                'verbose_name': 'Характеристика карточки',
                'verbose_name_plural': 'Характеристики карточки',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию автомобиля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.featureicon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.product')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики с иконками',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.product')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('main', 'Основные параметры'), ('engine', 'Двигатель'), ('weight', 'Весовые параметры'), ('transmission', 'Трансмиссия'), ('brakes', 'Система тормозов и шин'), ('comfort', 'Удобства'), ('superstructure', 'Надстройка'), ('cabin', 'Кабина'), ('additional', 'Дополнительные параметры')], max_length=50, verbose_name='Категория')),
                ('text', models.CharField(max_length=500, verbose_name='Параметр')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Параметр')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Параметр')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Параметр')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='main.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры машины',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Fargʻona viloyati', 'Fargʻona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Qoraqalpogʻiston Respublikasi', 'Qoraqalpogʻiston Respublikasi')], max_length=100, verbose_name='Регион')),
                ('resume', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Резюме')),
                ('applicant_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('applicant_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('applicant_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Рассмотрено')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий HR')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Заявки - Заявка на вакансию',
                'verbose_name_plural': 'Заявки - Заявки на вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Условие')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Условие')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Условие')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Условие')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyIdealCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Качество')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Качество')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Качество')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Качество')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_candidates', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'Портрет кандидата',
                'verbose_name_plural': 'Портрет кандидата',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Требование')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Требование')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Требование')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Требование')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('text_uz', models.TextField(null=True, verbose_name='Описание')),
                ('text_ru', models.TextField(null=True, verbose_name='Описание')),
                ('text_en', models.TextField(null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'Обязанность',
                'verbose_name_plural': 'Обязанности',
                'ordering': ['order'],
            },
        ),
    ]
