import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoCRMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('expires_at', models.DateTimeField(verbose_name='Р В Р РЋР С“Р РЋРІР‚С™Р В Р’ВµР В РЎвЂќР В Р’В°Р В Р’ВµР РЋРІР‚С™')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Р В РЎСџР В РЎвЂўР РЋР С“Р В Р’В»Р В Р’ВµР В РўвЂР В Р вЂ¦Р В Р’ВµР В Р’Вµ Р В РЎвЂўР В Р’В±Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
            ],
            options={
                'verbose_name': 'amoCRM Р В РЎС›Р В РЎвЂўР В РЎвЂќР В Р’ВµР В Р вЂ¦',
                'verbose_name_plural': 'amoCRM Р В РЎС›Р В РЎвЂўР В РЎвЂќР В Р’ВµР В Р вЂ¦Р РЋРІР‚в„–',
            },
        ),
        migrations.CreateModel(
            name='FeatureIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('icon', models.FileField(upload_to='features/icons/', verbose_name='Р В Р В РЎвЂќР В РЎвЂўР В Р вЂ¦Р В РЎвЂќР В Р’В°')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
            ],
            options={
                'verbose_name': 'Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’ВµР В Р вЂ¦Р РЋРІР‚С™ - Р В Р В РЎвЂќР В РЎвЂўР В Р вЂ¦Р В РЎвЂќР В Р’В°',
                'verbose_name_plural': 'Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’ВµР В Р вЂ¦Р РЋРІР‚С™ - Р В Р В РЎвЂќР В РЎвЂўР В Р вЂ¦Р В РЎвЂќР В РЎвЂ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РЎР В РЎвЂўР В РўвЂР В Р’ВµР В Р’В»Р В РЎвЂ')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РЎР В РЎвЂўР В РўвЂР В Р’ВµР В Р’В»Р В РЎвЂ')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РЎР В РЎвЂўР В РўвЂР В Р’ВµР В Р’В»Р В РЎвЂ')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РЎР В РЎвЂўР В РўвЂР В Р’ВµР В Р’В»Р В РЎвЂ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='Р В РІР‚СљР В Р’В»Р В Р’В°Р В Р вЂ Р В Р вЂ¦Р В РЎвЂўР В Р’Вµ Р В РЎвЂР В Р’В·Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='products/cards/', verbose_name='Р В Р В Р’В·Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В»Р РЋР РЏ Р В РЎвЂќР В Р’В°Р РЋР вЂљР РЋРІР‚С™Р В РЎвЂўР РЋРІР‚РЋР В РЎвЂќР В РЎвЂ')),
                ('slider_image', models.ImageField(blank=True, help_text='Р В Р’В Р В Р’ВµР В РЎвЂќР В РЎвЂўР В РЎР В Р’ВµР В Р вЂ¦Р В РўвЂР РЋРЎвЂњР В Р’ВµР В РЎР РЋРІР‚в„–Р В РІвЂћвЂ“ Р РЋР вЂљР В Р’В°Р В Р’В·Р В РЎР В Р’ВµР РЋР вЂљ: 420x210px. Р В РІР‚СћР РЋР С“Р В Р’В»Р В РЎвЂ Р В Р вЂ¦Р В Р’Вµ Р РЋРЎвЂњР В РЎвЂќР В Р’В°Р В Р’В·Р В Р’В°Р В Р вЂ¦Р В РЎвЂў, Р В РЎвЂР РЋР С“Р В РЎвЂ”Р В РЎвЂўР В Р’В»Р РЋР Р‰Р В Р’В·Р РЋРЎвЂњР В Р’ВµР РЋРІР‚С™Р РЋР С“Р РЋР РЏ main_image', null=True, upload_to='products/slider/', verbose_name='Р В Р В Р’В·Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_year', models.CharField(default='2025', help_text='Р В РЎвЂєР РЋРІР‚С™Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’В°Р В Р’ВµР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р вЂ  Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’Вµ', max_length=4, verbose_name='Р В РІР‚СљР В РЎвЂўР В РўвЂ Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_price', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '434 000 000 sum'", max_length=100, null=True, verbose_name='Р В Р’В¦Р В Р’ВµР В Р вЂ¦Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_price_uz', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '434 000 000 sum'", max_length=100, null=True, verbose_name='Р В Р’В¦Р В Р’ВµР В Р вЂ¦Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_price_ru', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '434 000 000 sum'", max_length=100, null=True, verbose_name='Р В Р’В¦Р В Р’ВµР В Р вЂ¦Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_price_en', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '434 000 000 sum'", max_length=100, null=True, verbose_name='Р В Р’В¦Р В Р’ВµР В Р вЂ¦Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_power', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '185 o.k.'", max_length=50, null=True, verbose_name='Р В РЎС™Р В РЎвЂўР РЋРІР‚В°Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰ Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_power_uz', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '185 o.k.'", max_length=50, null=True, verbose_name='Р В РЎС™Р В РЎвЂўР РЋРІР‚В°Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰ Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_power_ru', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '185 o.k.'", max_length=50, null=True, verbose_name='Р В РЎС™Р В РЎвЂўР РЋРІР‚В°Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰ Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_power_en', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '185 o.k.'", max_length=50, null=True, verbose_name='Р В РЎС™Р В РЎвЂўР РЋРІР‚В°Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰ Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_fuel_consumption', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '17 L/100km'", max_length=50, null=True, verbose_name='Р В Р’В Р В Р’В°Р РЋР С“Р РЋРІР‚В¦Р В РЎвЂўР В РўвЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎвЂ”Р В Р’В»Р В РЎвЂР В Р вЂ Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_fuel_consumption_uz', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '17 L/100km'", max_length=50, null=True, verbose_name='Р В Р’В Р В Р’В°Р РЋР С“Р РЋРІР‚В¦Р В РЎвЂўР В РўвЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎвЂ”Р В Р’В»Р В РЎвЂР В Р вЂ Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_fuel_consumption_ru', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '17 L/100km'", max_length=50, null=True, verbose_name='Р В Р’В Р В Р’В°Р РЋР С“Р РЋРІР‚В¦Р В РЎвЂўР В РўвЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎвЂ”Р В Р’В»Р В РЎвЂР В Р вЂ Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_fuel_consumption_en', models.CharField(blank=True, help_text="Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: '17 L/100km'", max_length=50, null=True, verbose_name='Р В Р’В Р В Р’В°Р РЋР С“Р РЋРІР‚В¦Р В РЎвЂўР В РўвЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎвЂ”Р В Р’В»Р В РЎвЂР В Р вЂ Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°')),
                ('slider_order', models.PositiveIntegerField(default=0, help_text='Р В Р’В§Р В Р’ВµР В РЎ Р В Р’В±Р В РЎвЂўР В Р’В»Р РЋР Р‰Р РЋРІвЂљВ¬Р В Р’Вµ Р РЋРІР‚РЋР В РЎвЂР РЋР С“Р В Р’В»Р В РЎвЂў, Р РЋРІР‚С™Р В Р’ВµР В РЎ Р РЋР вЂљР В Р’В°Р В Р вЂ¦Р РЋР Р‰Р РЋРІвЂљВ¬Р В Р’Вµ Р В РЎвЂ”Р В РЎвЂўР РЋР РЏР В Р вЂ Р В РЎвЂР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р вЂ  Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’Вµ', verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ Р В Р вЂ  Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљР В Р’Вµ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Р В РЎвЂ™Р В РЎвЂќР РЋРІР‚С™Р В РЎвЂР В Р вЂ Р В Р’ВµР В Р вЂ¦')),
                ('is_featured', models.BooleanField(default=False, help_text='Р В РЎСџР РЋР вЂљР В РЎвЂўР В РўвЂР РЋРЎвЂњР В РЎвЂќР РЋРІР‚С™ Р В Р’В±Р РЋРЎвЂњР В РўвЂР В Р’ВµР РЋРІР‚С™ Р В РўвЂР В РЎвЂўР В Р’В±Р В Р’В°Р В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦ Р В Р вЂ  Р В РЎвЂ“Р В Р’В»Р В Р’В°Р В Р вЂ Р В Р вЂ¦Р РЋРІР‚в„–Р В РІвЂћвЂ“ Р РЋР С“Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р В РўвЂР В Р’ВµР РЋР вЂљ', verbose_name='Р В РЎСџР В РЎвЂўР В РЎвЂќР В Р’В°Р В Р’В·Р РЋРІР‚в„–Р В Р вЂ Р В Р’В°Р РЋРІР‚С™Р РЋР Р‰ Р В Р вЂ¦Р В Р’В° Р В РЎвЂ“Р В Р’В»Р В Р’В°Р В Р вЂ Р В Р вЂ¦Р В РЎвЂўР В РІвЂћвЂ“')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р РЋР С“Р В РЎвЂўР В Р’В·Р В РўвЂР В Р’В°Р В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РЎвЂўР В Р’В±Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
            ],
            options={
                'verbose_name': 'Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’ВµР В Р вЂ¦Р РЋРІР‚С™ - Р В РЎвЂ™Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎР В РЎвЂўР В Р’В±Р В РЎвЂР В Р’В»Р РЋР Р‰',
                'verbose_name_plural': 'Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’ВµР В Р вЂ¦Р РЋРІР‚С™ - Р В РЎвЂ™Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎР В РЎвЂўР В Р’В±Р В РЎвЂР В Р’В»Р В РЎвЂ',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('hero_image', models.ImageField(blank=True, help_text='Р В Р В Р’В·Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р РЋРІР‚С™Р РЋР вЂљР В Р’В°Р В Р вЂ¦Р В РЎвЂР РЋРІР‚В Р РЋРІР‚в„– Р В РЎвЂќР В Р’В°Р РЋРІР‚С™Р В Р’ВµР В РЎвЂ“Р В РЎвЂўР РЋР вЂљР В РЎвЂР В РЎвЂ', null=True, upload_to='categories/heroes/', verbose_name='Р В Р’В¤Р В РЎвЂўР В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В Р’Вµ Р В РЎвЂР В Р’В·Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Р В Р В РЎвЂќР В РЎвЂўР В Р вЂ¦Р В РЎвЂќР В Р’В°')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Р В РЎвЂ™Р В РЎвЂќР РЋРІР‚С™Р В РЎвЂР В Р вЂ Р В Р вЂ¦Р В Р’В°')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р РЋР С“Р В РЎвЂўР В Р’В·Р В РўвЂР В Р’В°Р В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
            ],
            options={
                'verbose_name': 'Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’ВµР В Р вЂ¦Р РЋРІР‚С™ - Р В РЎС™Р В Р’В°Р РЋР вЂљР В РЎвЂќР В Р’В°',
                'verbose_name_plural': 'Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’ВµР В Р вЂ¦Р РЋРІР‚С™ - Р В РЎС™Р В Р’В°Р РЋР вЂљР В РЎвЂќР В Р’В° Р В Р’В°Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎР В РЎвЂўР В Р’В±Р В РЎвЂР В Р’В»Р РЋР РЏ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('short_description_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('short_description_ru', models.TextField(blank=True, max_length=500, null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('short_description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('contact_info', models.TextField(default='Р В РЎСџР РЋР вЂљР В РЎвЂР РЋР С“Р РЋРІР‚в„–Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р РЋРІР‚С™Р В Р’Вµ Р РЋР вЂљР В Р’ВµР В Р’В·Р РЋР вЂ№Р В РЎР В Р’Вµ Р В Р вЂ¦Р В Р’В° info@autoliga.uz', verbose_name='Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р В РЎвЂќР РЋРІР‚С™Р РЋРІР‚в„–')),
                ('contact_info_uz', models.TextField(default='Р В РЎСџР РЋР вЂљР В РЎвЂР РЋР С“Р РЋРІР‚в„–Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р РЋРІР‚С™Р В Р’Вµ Р РЋР вЂљР В Р’ВµР В Р’В·Р РЋР вЂ№Р В РЎР В Р’Вµ Р В Р вЂ¦Р В Р’В° info@autoliga.uz', null=True, verbose_name='Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р В РЎвЂќР РЋРІР‚С™Р РЋРІР‚в„–')),
                ('contact_info_ru', models.TextField(default='Р В РЎСџР РЋР вЂљР В РЎвЂР РЋР С“Р РЋРІР‚в„–Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р РЋРІР‚С™Р В Р’Вµ Р РЋР вЂљР В Р’ВµР В Р’В·Р РЋР вЂ№Р В РЎР В Р’Вµ Р В Р вЂ¦Р В Р’В° info@autoliga.uz', null=True, verbose_name='Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р В РЎвЂќР РЋРІР‚С™Р РЋРІР‚в„–')),
                ('contact_info_en', models.TextField(default='Р В РЎСџР РЋР вЂљР В РЎвЂР РЋР С“Р РЋРІР‚в„–Р В Р’В»Р В Р’В°Р В РІвЂћвЂ“Р РЋРІР‚С™Р В Р’Вµ Р РЋР вЂљР В Р’ВµР В Р’В·Р РЋР вЂ№Р В РЎР В Р’Вµ Р В Р вЂ¦Р В Р’В° info@autoliga.uz', null=True, verbose_name='Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р В РЎвЂќР РЋРІР‚С™Р РЋРІР‚в„–')),
                ('is_active', models.BooleanField(default=True, verbose_name='Р В РЎвЂ™Р В РЎвЂќР РЋРІР‚С™Р В РЎвЂР В Р вЂ Р В Р вЂ¦Р В Р’В°')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р РЋР С“Р В РЎвЂўР В Р’В·Р В РўвЂР В Р’В°Р В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РЎвЂўР В Р’В±Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
            ],
            options={
                'verbose_name': 'Р В РІР‚в„ўР В Р’В°Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р РЋР С“Р В РЎвЂР В РЎвЂ - Р В РІР‚в„ўР В Р’В°Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р РЋР С“Р В РЎвЂР РЋР РЏ',
                'verbose_name_plural': 'Р В РІР‚в„ўР В Р’В°Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р РЋР С“Р В РЎвЂР В РЎвЂ - Р В РІР‚в„ўР В Р’В°Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р РЋР С“Р В РЎвЂР В РЎвЂ',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Р В Р В РЎР РЋР РЏ')),
                ('region', models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('FargР С™Р’В»ona viloyati', 'FargР С™Р’В»ona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('QoraqalpogР С™Р’В»iston Respublikasi', 'QoraqalpogР С™Р’В»iston Respublikasi')], max_length=100, verbose_name='Р В Р’В Р В Р’ВµР В РЎвЂ“Р В РЎвЂР В РЎвЂўР В Р вЂ¦')),
                ('phone', models.CharField(max_length=50, verbose_name='Р В РЎС›Р В Р’ВµР В Р’В»Р В Р’ВµР РЋРІР‚С›Р В РЎвЂўР В Р вЂ¦')),
                ('product', models.CharField(blank=True, help_text='Р В РЎв„ўР В Р’В°Р В РЎвЂќР РЋРЎвЂњР РЋР вЂ№ Р В РЎР В РЎвЂўР В РўвЂР В Р’ВµР В Р’В»Р РЋР Р‰ Р В Р’В°Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎР В РЎвЂўР В Р’В±Р В РЎвЂР В Р’В»Р РЋР РЏ Р В РЎвЂР В Р вЂ¦Р РЋРІР‚С™Р В Р’ВµР РЋР вЂљР В Р’ВµР РЋР С“Р РЋРЎвЂњР В Р’ВµР РЋРІР‚С™ Р В РЎвЂќР В Р’В»Р В РЎвЂР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°', max_length=200, null=True, verbose_name='Р В РЎС™Р В РЎвЂўР В РўвЂР В Р’ВµР В Р’В»Р РЋР Р‰ Р РЋРІР‚С™Р В Р’ВµР РЋРІР‚В¦Р В Р вЂ¦Р В РЎвЂР В РЎвЂќР В РЎвЂ')),
                ('referer', models.URLField(blank=True, help_text='URL Р РЋР С“Р РЋРІР‚С™Р РЋР вЂљР В Р’В°Р В Р вЂ¦Р В РЎвЂР РЋРІР‚В Р РЋРІР‚в„–, Р РЋР С“ Р В РЎвЂќР В РЎвЂўР РЋРІР‚С™Р В РЎвЂўР РЋР вЂљР В РЎвЂўР В РІвЂћвЂ“ Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В Р’В° Р В Р’В·Р В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В Р’В°', max_length=500, null=True, verbose_name='Referer (Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂќР РЋРЎвЂњР В РўвЂР В Р’В° Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР РЋРІвЂљВ¬Р РЋРІР‚Р В Р’В»)')),
                ('utm_data', models.TextField(blank=True, help_text='UTM Р В РЎР В Р’ВµР РЋРІР‚С™Р В РЎвЂќР В РЎвЂ Р В Р вЂ  JSON Р РЋРІР‚С›Р В РЎвЂўР РЋР вЂљР В РЎР В Р’В°Р РЋРІР‚С™Р В Р’Вµ', null=True, verbose_name='UTM Р В РЎР В Р’ВµР РЋРІР‚С™Р В РЎвЂќР В РЎвЂ')),
                ('visitor_uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='amoCRM Visitor UID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В°')),
                ('message', models.TextField(blank=True, default='', verbose_name='Р В Р Р‹Р В РЎвЂўР В РЎвЂўР В Р’В±Р РЋРІР‚В°Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('status', models.CharField(choices=[('new', 'Р В РЎСљР В РЎвЂўР В Р вЂ Р В Р’В°Р РЋР РЏ'), ('in_process', 'Р В РІР‚в„ў Р В РЎвЂ”Р РЋР вЂљР В РЎвЂўР РЋРІР‚В Р В Р’ВµР РЋР С“Р РЋР С“Р В Р’Вµ'), ('done', 'Р В РЎвЂєР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В±Р В РЎвЂўР РЋРІР‚С™Р В Р’В°Р В Р вЂ¦Р В Р’В°')], default='new', max_length=20, verbose_name='Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋРІР‚С™Р РЋРЎвЂњР РЋР С“')),
                ('priority', models.CharField(choices=[('high', 'Р В РІР‚в„ўР РЋРІР‚в„–Р РЋР С“Р В РЎвЂўР В РЎвЂќР В РЎвЂР В РІвЂћвЂ“'), ('medium', 'Р В Р Р‹Р РЋР вЂљР В Р’ВµР В РўвЂР В Р вЂ¦Р В РЎвЂР В РІвЂћвЂ“'), ('low', 'Р В РЎСљР В РЎвЂР В Р’В·Р В РЎвЂќР В РЎвЂР В РІвЂћвЂ“')], default='medium', max_length=10, verbose_name='Р В РЎСџР РЋР вЂљР В РЎвЂР В РЎвЂўР РЋР вЂљР В РЎвЂР РЋРІР‚С™Р В Р’ВµР РЋРІР‚С™')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Р В РЎв„ўР В РЎвЂўР В РЎР В РЎР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР В РЎвЂР В РІвЂћвЂ“')),
                ('amocrm_status', models.CharField(choices=[('pending', 'Р В РЎвЂєР В Р’В¶Р В РЎвЂР В РўвЂР В Р’В°Р В Р’ВµР РЋРІР‚С™ Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В РЎвЂќР В РЎвЂ'), ('sent', 'Р В Р в‚¬Р РЋР С“Р В РЎвЂ”Р В Р’ВµР РЋРІвЂљВ¬Р В Р вЂ¦Р В РЎвЂў Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В РЎвЂў'), ('failed', 'Р В РЎвЂєР РЋРІвЂљВ¬Р В РЎвЂР В Р’В±Р В РЎвЂќР В Р’В° Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В РЎвЂќР В РЎвЂ')], db_index=True, default='pending', help_text='Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋРІР‚С™Р РЋРЎвЂњР РЋР С“ Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В РЎвЂќР В РЎвЂ Р В Р вЂ  amoCRM', max_length=20, verbose_name='Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋРІР‚С™Р РЋРЎвЂњР РЋР С“ amoCRM')),
                ('amocrm_lead_id', models.CharField(blank=True, help_text='ID Р В Р’В»Р В РЎвЂР В РўвЂР В Р’В° Р В РЎвЂ”Р В РЎвЂўР РЋР С“Р В Р’В»Р В Р’Вµ Р РЋРЎвЂњР РЋР С“Р В РЎвЂ”Р В Р’ВµР РЋРІвЂљВ¬Р В Р вЂ¦Р В РЎвЂўР В РІвЂћвЂ“ Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В РЎвЂќР В РЎвЂ', max_length=50, null=True, verbose_name='ID Р В Р’В»Р В РЎвЂР В РўвЂР В Р’В° Р В Р вЂ  amoCRM')),
                ('amocrm_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В РЎвЂќР В РЎвЂ Р В Р вЂ  amoCRM')),
                ('amocrm_error', models.TextField(blank=True, help_text='Р В РЎС›Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™ Р В РЎвЂ”Р В РЎвЂўР РЋР С“Р В Р’В»Р В Р’ВµР В РўвЂР В Р вЂ¦Р В Р’ВµР В РІвЂћвЂ“ Р В РЎвЂўР РЋРІвЂљВ¬Р В РЎвЂР В Р’В±Р В РЎвЂќР В РЎвЂ Р В РЎвЂ”Р РЋР вЂљР В РЎвЂ Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В РЎвЂќР В Р’Вµ', null=True, verbose_name='Р В РЎвЂєР РЋРІвЂљВ¬Р В РЎвЂР В Р’В±Р В РЎвЂќР В Р’В° amoCRM')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uz_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Р В РЎС™Р В Р’ВµР В Р вЂ¦Р В Р’ВµР В РўвЂР В Р’В¶Р В Р’ВµР РЋР вЂљ')),
            ],
            options={
                'verbose_name': 'Р В РІР‚вЂќР В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В РЎвЂ - Р В РЎвЂєР В Р’В±Р РЋРІР‚В°Р В Р’В°Р РЋР РЏ Р В Р’В·Р В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В Р’В°',
                'verbose_name_plural': 'Р В РІР‚вЂќР В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В РЎвЂ - Р В РЎвЂєР В Р’В±Р РЋРІР‚В°Р В РЎвЂР В Р’Вµ Р В Р’В·Р В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В РЎвЂ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ')),
                ('desc', models.TextField(help_text='Р В РЎвЂєР РЋРІР‚С™Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’В°Р В Р’ВµР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р вЂ  Р В РЎвЂ”Р РЋР вЂљР В Р’ВµР В Р вЂ Р РЋР Р‰Р РЋР вЂ№ Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В РЎвЂ', max_length=200, verbose_name='Р В РЎв„ўР РЋР вЂљР В Р’В°Р РЋРІР‚С™Р В РЎвЂќР В РЎвЂўР В Р’Вµ Р В РЎвЂўР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В»Р РЋР РЏ Р В РЎвЂќР В Р’В°Р РЋР вЂљР РЋРІР‚С™Р В РЎвЂўР РЋРІР‚РЋР В РЎвЂќР В РЎвЂ')),
                ('desc_uz', models.TextField(help_text='Р В РЎвЂєР РЋРІР‚С™Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’В°Р В Р’ВµР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р вЂ  Р В РЎвЂ”Р РЋР вЂљР В Р’ВµР В Р вЂ Р РЋР Р‰Р РЋР вЂ№ Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В РЎвЂ', max_length=200, null=True, verbose_name='Р В РЎв„ўР РЋР вЂљР В Р’В°Р РЋРІР‚С™Р В РЎвЂќР В РЎвЂўР В Р’Вµ Р В РЎвЂўР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В»Р РЋР РЏ Р В РЎвЂќР В Р’В°Р РЋР вЂљР РЋРІР‚С™Р В РЎвЂўР РЋРІР‚РЋР В РЎвЂќР В РЎвЂ')),
                ('desc_ru', models.TextField(help_text='Р В РЎвЂєР РЋРІР‚С™Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’В°Р В Р’ВµР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р вЂ  Р В РЎвЂ”Р РЋР вЂљР В Р’ВµР В Р вЂ Р РЋР Р‰Р РЋР вЂ№ Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В РЎвЂ', max_length=200, null=True, verbose_name='Р В РЎв„ўР РЋР вЂљР В Р’В°Р РЋРІР‚С™Р В РЎвЂќР В РЎвЂўР В Р’Вµ Р В РЎвЂўР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В»Р РЋР РЏ Р В РЎвЂќР В Р’В°Р РЋР вЂљР РЋРІР‚С™Р В РЎвЂўР РЋРІР‚РЋР В РЎвЂќР В РЎвЂ')),
                ('desc_en', models.TextField(help_text='Р В РЎвЂєР РЋРІР‚С™Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’В°Р В Р’ВµР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р вЂ  Р В РЎвЂ”Р РЋР вЂљР В Р’ВµР В Р вЂ Р РЋР Р‰Р РЋР вЂ№ Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В РЎвЂ', max_length=200, null=True, verbose_name='Р В РЎв„ўР РЋР вЂљР В Р’В°Р РЋРІР‚С™Р В РЎвЂќР В РЎвЂўР В Р’Вµ Р В РЎвЂўР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В»Р РЋР РЏ Р В РЎвЂќР В Р’В°Р РЋР вЂљР РЋРІР‚С™Р В РЎвЂўР РЋРІР‚РЋР В РЎвЂќР В РЎвЂ')),
                ('slug', models.SlugField(blank=True, help_text='Р В РІР‚СљР В Р’ВµР В Р вЂ¦Р В Р’ВµР РЋР вЂљР В РЎвЂР РЋР вЂљР РЋРЎвЂњР В Р’ВµР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р’В°Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎР В Р’В°Р РЋРІР‚С™Р В РЎвЂР РЋРІР‚РЋР В Р’ВµР РЋР С“Р В РЎвЂќР В РЎвЂ Р В РЎвЂР В Р’В· Р В Р’В·Р В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂќР В Р’В°', max_length=255, unique=True, verbose_name='URL')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Р В Р’В¤Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂў Р В Р’В°Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР РЋР вЂљР В Р’В°')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='news/previews/', verbose_name='Р В РІР‚СљР В Р’В»Р В Р’В°Р В Р вЂ Р В Р вЂ¦Р В РЎвЂўР В Р’Вµ Р РЋРІР‚С›Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂў')),
                ('is_active', models.BooleanField(default=True, help_text='Р В РЎСџР В РЎвЂўР В РЎвЂќР В Р’В°Р В Р’В·Р РЋРІР‚в„–Р В Р вЂ Р В Р’В°Р РЋРІР‚С™Р РЋР Р‰ Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰ Р В Р вЂ¦Р В Р’В° Р РЋР С“Р В Р’В°Р В РІвЂћвЂ“Р РЋРІР‚С™Р В Р’Вµ', verbose_name='Р В РЎвЂ™Р В РЎвЂќР РЋРІР‚С™Р В РЎвЂР В Р вЂ Р В Р вЂ¦Р В Р’В°')),
                ('order', models.PositiveIntegerField(default=0, help_text='Р В Р’В§Р В Р’ВµР В РЎ Р В Р’В±Р В РЎвЂўР В Р’В»Р РЋР Р‰Р РЋРІвЂљВ¬Р В Р’Вµ Р РЋРІР‚РЋР В РЎвЂР РЋР С“Р В Р’В»Р В РЎвЂў, Р РЋРІР‚С™Р В Р’ВµР В РЎ Р В Р вЂ Р РЋРІР‚в„–Р РЋРІвЂљВ¬Р В Р’Вµ Р В Р вЂ  Р РЋР С“Р В РЎвЂ”Р В РЎвЂР РЋР С“Р В РЎвЂќР В Р’Вµ', verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('created_at', models.DateField(help_text='Р В РІР‚в„ўР В Р вЂ Р В Р’ВµР В РўвЂР В РЎвЂР РЋРІР‚С™Р В Р’Вµ Р В РўвЂР В Р’В°Р РЋРІР‚С™Р РЋРЎвЂњ Р В РЎвЂ”Р РЋРЎвЂњР В Р’В±Р В Р’В»Р В РЎвЂР В РЎвЂќР В Р’В°Р РЋРІР‚В Р В РЎвЂР В РЎвЂ Р В Р вЂ Р РЋР вЂљР РЋРЎвЂњР РЋРІР‚РЋР В Р вЂ¦Р РЋРЎвЂњР РЋР вЂ№', verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РЎвЂ”Р РЋРЎвЂњР В Р’В±Р В Р’В»Р В РЎвЂР В РЎвЂќР В Р’В°Р РЋРІР‚В Р В РЎвЂР В РЎвЂ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РЎвЂўР В Р’В±Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Р В РЎвЂ™Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР РЋР вЂљ')),
            ],
            options={
                'verbose_name': ' - Р В РЎСљР В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰',
                'verbose_name_plural': 'Р В РЎв„ўР В РЎвЂўР В Р вЂ¦Р РЋРІР‚С™Р В Р’ВµР В Р вЂ¦Р РЋРІР‚С™ - Р В РЎСљР В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В РЎвЂ',
                'ordering': ['-order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Р В РЎС›Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™'), ('image', 'Р В Р В Р’В·Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ'), ('youtube', 'YouTube Р В Р вЂ Р В РЎвЂР В РўвЂР В Р’ВµР В РЎвЂў'), ('video', 'Р В РІР‚в„ўР В РЎвЂР В РўвЂР В Р’ВµР В РЎвЂў Р РЋРІР‚С›Р В Р’В°Р В РІвЂћвЂ“Р В Р’В»')], max_length=10, verbose_name='Р В РЎС›Р В РЎвЂР В РЎвЂ” Р В Р’В±Р В Р’В»Р В РЎвЂўР В РЎвЂќР В Р’В°')),
                ('title', models.CharField(blank=True, help_text='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ H3 Р В РЎвЂ”Р В Р’ВµР РЋР вЂљР В Р’ВµР В РўвЂ Р РЋРІР‚С™Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™Р В РЎвЂўР В Р вЂ Р РЋРІР‚в„–Р В РЎ Р В Р’В±Р В Р’В»Р В РЎвЂўР В РЎвЂќР В РЎвЂўР В РЎ', max_length=500, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ (Р В Р вЂ¦Р В Р’ВµР В РЎвЂўР В Р’В±Р РЋР РЏР В Р’В·Р В Р’В°Р РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰Р В Р вЂ¦Р В РЎвЂў)')),
                ('title_uz', models.CharField(blank=True, help_text='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ H3 Р В РЎвЂ”Р В Р’ВµР РЋР вЂљР В Р’ВµР В РўвЂ Р РЋРІР‚С™Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™Р В РЎвЂўР В Р вЂ Р РЋРІР‚в„–Р В РЎ Р В Р’В±Р В Р’В»Р В РЎвЂўР В РЎвЂќР В РЎвЂўР В РЎ', max_length=500, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ (Р В Р вЂ¦Р В Р’ВµР В РЎвЂўР В Р’В±Р РЋР РЏР В Р’В·Р В Р’В°Р РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰Р В Р вЂ¦Р В РЎвЂў)')),
                ('title_ru', models.CharField(blank=True, help_text='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ H3 Р В РЎвЂ”Р В Р’ВµР РЋР вЂљР В Р’ВµР В РўвЂ Р РЋРІР‚С™Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™Р В РЎвЂўР В Р вЂ Р РЋРІР‚в„–Р В РЎ Р В Р’В±Р В Р’В»Р В РЎвЂўР В РЎвЂќР В РЎвЂўР В РЎ', max_length=500, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ (Р В Р вЂ¦Р В Р’ВµР В РЎвЂўР В Р’В±Р РЋР РЏР В Р’В·Р В Р’В°Р РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰Р В Р вЂ¦Р В РЎвЂў)')),
                ('title_en', models.CharField(blank=True, help_text='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ H3 Р В РЎвЂ”Р В Р’ВµР РЋР вЂљР В Р’ВµР В РўвЂ Р РЋРІР‚С™Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™Р В РЎвЂўР В Р вЂ Р РЋРІР‚в„–Р В РЎ Р В Р’В±Р В Р’В»Р В РЎвЂўР В РЎвЂќР В РЎвЂўР В РЎ', max_length=500, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ (Р В Р вЂ¦Р В Р’ВµР В РЎвЂўР В Р’В±Р РЋР РЏР В Р’В·Р В Р’В°Р РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰Р В Р вЂ¦Р В РЎвЂў)')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Р В РЎС›Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™')),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Р В РЎС›Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™')),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Р В РЎС›Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™')),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Р В РЎС›Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Р В Р’В¤Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂў')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube Р РЋР С“Р РЋР С“Р РЋРІР‚в„–Р В Р’В»Р В РЎвЂќР В Р’В°')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='news/videos/', verbose_name='Р В РІР‚в„ўР В РЎвЂР В РўвЂР В Р’ВµР В РЎвЂў Р РЋРІР‚С›Р В Р’В°Р В РІвЂћвЂ“Р В Р’В»')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.news', verbose_name='Р В РЎСљР В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰')),
            ],
            options={
                'verbose_name': 'Р В РІР‚Р В Р’В»Р В РЎвЂўР В РЎвЂќ Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В РЎвЂ',
                'verbose_name_plural': 'Р В РІР‚Р В Р’В»Р В РЎвЂўР В РЎвЂќР В РЎвЂ Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В Р’ВµР В РІвЂћвЂ“',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Р В РІР‚вЂќР В Р вЂ¦Р В Р’В°Р РЋРІР‚РЋР В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('value_uz', models.CharField(max_length=100, null=True, verbose_name='Р В РІР‚вЂќР В Р вЂ¦Р В Р’В°Р РЋРІР‚РЋР В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('value_ru', models.CharField(max_length=100, null=True, verbose_name='Р В РІР‚вЂќР В Р вЂ¦Р В Р’В°Р РЋРІР‚РЋР В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('value_en', models.CharField(max_length=100, null=True, verbose_name='Р В РІР‚вЂќР В Р вЂ¦Р В Р’В°Р РЋРІР‚РЋР В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.featureicon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_specs', to='main.product')),
            ],
            options={
                'verbose_name': 'Р В РўС’Р В Р’В°Р РЋР вЂљР В Р’В°Р В РЎвЂќР РЋРІР‚С™Р В Р’ВµР РЋР вЂљР В РЎвЂР РЋР С“Р РЋРІР‚С™Р В РЎвЂР В РЎвЂќР В Р’В° Р В РЎвЂќР В Р’В°Р РЋР вЂљР РЋРІР‚С™Р В РЎвЂўР РЋРІР‚РЋР В РЎвЂќР В РЎвЂ',
                'verbose_name_plural': 'Р В РўС’Р В Р’В°Р РЋР вЂљР В Р’В°Р В РЎвЂќР РЋРІР‚С™Р В Р’ВµР РЋР вЂљР В РЎвЂР РЋР С“Р РЋРІР‚С™Р В РЎвЂР В РЎвЂќР В РЎвЂ Р В РЎвЂќР В Р’В°Р РЋР вЂљР РЋРІР‚С™Р В РЎвЂўР РЋРІР‚РЋР В РЎвЂќР В РЎвЂ',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Р В РІР‚в„ўР РЋРІР‚в„–Р В Р’В±Р В Р’ВµР РЋР вЂљР В РЎвЂР РЋРІР‚С™Р В Р’Вµ Р В РЎвЂќР В Р’В°Р РЋРІР‚С™Р В Р’ВµР В РЎвЂ“Р В РЎвЂўР РЋР вЂљР В РЎвЂР РЋР вЂ№ Р В Р’В°Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎР В РЎвЂўР В Р’В±Р В РЎвЂР В Р’В»Р РЋР РЏ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productcategory', verbose_name='Р В РЎв„ўР В Р’В°Р РЋРІР‚С™Р В Р’ВµР В РЎвЂ“Р В РЎвЂўР РЋР вЂљР В РЎвЂР РЋР РЏ'),
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Р В РЎСљР В Р’В°Р В Р’В·Р В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.featureicon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.product')),
            ],
            options={
                'verbose_name': 'Р В РўС’Р В Р’В°Р РЋР вЂљР В Р’В°Р В РЎвЂќР РЋРІР‚С™Р В Р’ВµР РЋР вЂљР В РЎвЂР РЋР С“Р РЋРІР‚С™Р В РЎвЂР В РЎвЂќР В Р’В°',
                'verbose_name_plural': 'Р В РўС’Р В Р’В°Р РЋР вЂљР В Р’В°Р В РЎвЂќР РЋРІР‚С™Р В Р’ВµР РЋР вЂљР В РЎвЂР РЋР С“Р РЋРІР‚С™Р В РЎвЂР В РЎвЂќР В РЎвЂ Р РЋР С“ Р В РЎвЂР В РЎвЂќР В РЎвЂўР В Р вЂ¦Р В РЎвЂќР В Р’В°Р В РЎР В РЎвЂ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Р В Р В Р’В·Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.product')),
            ],
            options={
                'verbose_name': 'Р В Р’В¤Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂў Р В РЎвЂ“Р В Р’В°Р В Р’В»Р В Р’ВµР РЋР вЂљР В Р’ВµР В РЎвЂ',
                'verbose_name_plural': 'Р В РІР‚СљР В Р’В°Р В Р’В»Р В Р’ВµР РЋР вЂљР В Р’ВµР РЋР РЏ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('main', 'Р В РЎвЂєР РЋР С“Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р В РЎвЂ”Р В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљР РЋРІР‚в„–'), ('engine', 'Р В РІР‚СњР В Р вЂ Р В РЎвЂР В РЎвЂ“Р В Р’В°Р РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰'), ('weight', 'Р В РІР‚в„ўР В Р’ВµР РЋР С“Р В РЎвЂўР В Р вЂ Р РЋРІР‚в„–Р В Р’Вµ Р В РЎвЂ”Р В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљР РЋРІР‚в„–'), ('transmission', 'Р В РЎС›Р РЋР вЂљР В Р’В°Р В Р вЂ¦Р РЋР С“Р В РЎР В РЎвЂР РЋР С“Р РЋР С“Р В РЎвЂР РЋР РЏ'), ('brakes', 'Р В Р Р‹Р В РЎвЂР РЋР С“Р РЋРІР‚С™Р В Р’ВµР В РЎР В Р’В° Р РЋРІР‚С™Р В РЎвЂўР РЋР вЂљР В РЎР В РЎвЂўР В Р’В·Р В РЎвЂўР В Р вЂ  Р В РЎвЂ Р РЋРІвЂљВ¬Р В РЎвЂР В Р вЂ¦'), ('comfort', 'Р В Р в‚¬Р В РўвЂР В РЎвЂўР В Р’В±Р РЋР С“Р РЋРІР‚С™Р В Р вЂ Р В Р’В°'), ('superstructure', 'Р В РЎСљР В Р’В°Р В РўвЂР РЋР С“Р РЋРІР‚С™Р РЋР вЂљР В РЎвЂўР В РІвЂћвЂ“Р В РЎвЂќР В Р’В°'), ('cabin', 'Р В РЎв„ўР В Р’В°Р В Р’В±Р В РЎвЂР В Р вЂ¦Р В Р’В°'), ('additional', 'Р В РІР‚СњР В РЎвЂўР В РЎвЂ”Р В РЎвЂўР В Р’В»Р В Р вЂ¦Р В РЎвЂР РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р В РЎвЂ”Р В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљР РЋРІР‚в„–')], max_length=50, verbose_name='Р В РЎв„ўР В Р’В°Р РЋРІР‚С™Р В Р’ВµР В РЎвЂ“Р В РЎвЂўР РЋР вЂљР В РЎвЂР РЋР РЏ')),
                ('text', models.CharField(max_length=500, verbose_name='Р В РЎСџР В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљ')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Р В РЎСџР В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљ')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Р В РЎСџР В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљ')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Р В РЎСџР В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='main.product', verbose_name='Р В РЎСџР РЋР вЂљР В РЎвЂўР В РўвЂР РЋРЎвЂњР В РЎвЂќР РЋРІР‚С™')),
            ],
            options={
                'verbose_name': 'Р В РЎСџР В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљ',
                'verbose_name_plural': 'Р В РЎСџР В Р’В°Р РЋР вЂљР В Р’В°Р В РЎР В Р’ВµР РЋРІР‚С™Р РЋР вЂљР РЋРІР‚в„– Р В РЎР В Р’В°Р РЋРІвЂљВ¬Р В РЎвЂР В Р вЂ¦Р РЋРІР‚в„–',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('FargР С™Р’В»ona viloyati', 'FargР С™Р’В»ona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('QoraqalpogР С™Р’В»iston Respublikasi', 'QoraqalpogР С™Р’В»iston Respublikasi')], max_length=100, verbose_name='Р В Р’В Р В Р’ВµР В РЎвЂ“Р В РЎвЂР В РЎвЂўР В Р вЂ¦')),
                ('resume', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Р В Р’В Р В Р’ВµР В Р’В·Р РЋР вЂ№Р В РЎР В Р’Вµ')),
                ('applicant_name', models.CharField(blank=True, max_length=255, verbose_name='Р В Р’В¤Р В Р В РЎвЂє')),
                ('applicant_phone', models.CharField(blank=True, max_length=50, verbose_name='Р В РЎС›Р В Р’ВµР В Р’В»Р В Р’ВµР РЋРІР‚С›Р В РЎвЂўР В Р вЂ¦')),
                ('applicant_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В°')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Р В Р’В Р В Р’В°Р РЋР С“Р РЋР С“Р В РЎР В РЎвЂўР РЋРІР‚С™Р РЋР вЂљР В Р’ВµР В Р вЂ¦Р В РЎвЂў')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Р В РЎв„ўР В РЎвЂўР В РЎР В РЎР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР В РЎвЂР В РІвЂћвЂ“ HR')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.vacancy', verbose_name='Р В РІР‚в„ўР В Р’В°Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р РЋР С“Р В РЎвЂР РЋР РЏ')),
            ],
            options={
                'verbose_name': 'Р В РІР‚вЂќР В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В РЎвЂ - Р В РІР‚вЂќР В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В Р’В° Р В Р вЂ¦Р В Р’В° Р В Р вЂ Р В Р’В°Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р РЋР С“Р В РЎвЂР РЋР вЂ№',
                'verbose_name_plural': 'Р В РІР‚вЂќР В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В РЎвЂ - Р В РІР‚вЂќР В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В РЎвЂ Р В Р вЂ¦Р В Р’В° Р В Р вЂ Р В Р’В°Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р РЋР С“Р В РЎвЂР В РЎвЂ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Р В Р в‚¬Р РЋР С“Р В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂР В Р’Вµ')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Р В Р в‚¬Р РЋР С“Р В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂР В Р’Вµ')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Р В Р в‚¬Р РЋР С“Р В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂР В Р’Вµ')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Р В Р в‚¬Р РЋР С“Р В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂР В Р’Вµ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'Р В Р в‚¬Р РЋР С“Р В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂР В Р’Вµ',
                'verbose_name_plural': 'Р В Р в‚¬Р РЋР С“Р В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂР РЋР РЏ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyIdealCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Р В РЎв„ўР В Р’В°Р РЋРІР‚РЋР В Р’ВµР РЋР С“Р РЋРІР‚С™Р В Р вЂ Р В РЎвЂў')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Р В РЎв„ўР В Р’В°Р РЋРІР‚РЋР В Р’ВµР РЋР С“Р РЋРІР‚С™Р В Р вЂ Р В РЎвЂў')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Р В РЎв„ўР В Р’В°Р РЋРІР‚РЋР В Р’ВµР РЋР С“Р РЋРІР‚С™Р В Р вЂ Р В РЎвЂў')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Р В РЎв„ўР В Р’В°Р РЋРІР‚РЋР В Р’ВµР РЋР С“Р РЋРІР‚С™Р В Р вЂ Р В РЎвЂў')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_candidates', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋРІР‚С™Р РЋР вЂљР В Р’ВµР РЋРІР‚С™ Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р В РўвЂР В РЎвЂР В РўвЂР В Р’В°Р РЋРІР‚С™Р В Р’В°',
                'verbose_name_plural': 'Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋРІР‚С™Р РЋР вЂљР В Р’ВµР РЋРІР‚С™ Р В РЎвЂќР В Р’В°Р В Р вЂ¦Р В РўвЂР В РЎвЂР В РўвЂР В Р’В°Р РЋРІР‚С™Р В Р’В°',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Р В РЎС›Р РЋР вЂљР В Р’ВµР В Р’В±Р В РЎвЂўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Р В РЎС›Р РЋР вЂљР В Р’ВµР В Р’В±Р В РЎвЂўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Р В РЎС›Р РЋР вЂљР В Р’ВµР В Р’В±Р В РЎвЂўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Р В РЎС›Р РЋР вЂљР В Р’ВµР В Р’В±Р В РЎвЂўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'Р В РЎС›Р РЋР вЂљР В Р’ВµР В Р’В±Р В РЎвЂўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ',
                'verbose_name_plural': 'Р В РЎС›Р РЋР вЂљР В Р’ВµР В Р’В±Р В РЎвЂўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР РЋР РЏ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Р В РІР‚вЂќР В Р’В°Р В РЎвЂ“Р В РЎвЂўР В Р’В»Р В РЎвЂўР В Р вЂ Р В РЎвЂўР В РЎвЂќ')),
                ('text', models.TextField(verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('text_uz', models.TextField(null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('text_ru', models.TextField(null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('text_en', models.TextField(null=True, verbose_name='Р В РЎвЂєР В РЎвЂ”Р В РЎвЂР РЋР С“Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'Р В РЎвЂєР В Р’В±Р РЋР РЏР В Р’В·Р В Р’В°Р В Р вЂ¦Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰',
                'verbose_name_plural': 'Р В РЎвЂєР В Р’В±Р РЋР РЏР В Р’В·Р В Р’В°Р В Р вЂ¦Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В РЎвЂ',
                'ordering': ['order'],
            },
        ),
    ]
