# Generated by Django 5.1.2 on 2026-02-25 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(help_text='«Например: двигатель, вес, кабина. Только латинские буквы и тире».', max_length=100, unique=True, verbose_name='«Слуг (кодекс)»')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Категория параметра',
                'verbose_name_plural': 'Категории параметров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'ordering': ['category__order', 'order'], 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры машины'},
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='main.parametercategory', verbose_name='Категория параметра'),
        ),
    ]
