# Generated by Django 5.1.2 on 2026-03-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parametercategory_name_en_parametercategory_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Foydalanuvchining Telegram ID si', null=True, verbose_name='Telegram ID'),
        ),
    ]
