# Generated by Django 5.1.2 on 2026-03-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactform_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ismi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Viloyat')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='telegram_id',
        ),
    ]
