# Generated by Django 5.1.2 on 2026-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_telegramuser_remove_contactform_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yosh'),
        ),
    ]
