# Generated by Django 5.1.2 on 2026-03-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_telegramuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('region', models.CharField(choices=[('qoraqalpogiston', "Qoraqalpog'iston Respublikasi"), ('xorazm', 'Xorazm viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('samarqand', 'Samarqand viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('toshkent-viloyati', 'Toshkent viloyati'), ('toshkent-shahri', 'Toshkent shahri'), ('namangan', 'Namangan viloyati'), ('andijon', 'Andijon viloyati'), ('fargona', "Farg'ona viloyati")], max_length=50, verbose_name='Viloyat')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Manzil')),
                ('address_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil')),
                ('address_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil')),
                ('address_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('working_hours', models.CharField(blank=True, help_text='Masalan: Du-Yak 9:00 - 18:00', max_length=100, verbose_name='Ish vaqti')),
                ('working_hours_uz', models.CharField(blank=True, help_text='Masalan: Du-Yak 9:00 - 18:00', max_length=100, null=True, verbose_name='Ish vaqti')),
                ('working_hours_ru', models.CharField(blank=True, help_text='Masalan: Du-Yak 9:00 - 18:00', max_length=100, null=True, verbose_name='Ish vaqti')),
                ('working_hours_en', models.CharField(blank=True, help_text='Masalan: Du-Yak 9:00 - 18:00', max_length=100, null=True, verbose_name='Ish vaqti')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dealers/logos/', verbose_name='Logo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Google Maps dan oling. Misol: 41.299496', max_digits=9, null=True, verbose_name='Kenglik (Latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Google Maps dan oling. Misol: 69.240073', max_digits=9, null=True, verbose_name='Uzunlik (Longitude)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': ' - Diler',
                'verbose_name_plural': 'Dilerlar - Diler markazlari',
                'ordering': ['order', 'name'],
            },
        ),
    ]
