# Generated by Django 5.1.2 on 2026-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='От 1 до 5', verbose_name='Оценка')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст отзыва')),
                ('avatar', models.ImageField(blank=True, help_text='Максимум 5 МБ, JPG/PNG', null=True, upload_to='reviews/avatars/%Y/%m/', verbose_name='Фото аватара')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('is_verified', models.BooleanField(default=False, help_text='Отображать значок «Проверено» рядом с именем', verbose_name='Проверен')),
                ('admin_comment', models.TextField(blank=True, help_text='Внутренний комментарий, не показывается на сайте', null=True, verbose_name='Комментарий модератора')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адрес отправителя', null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
