# Generated by Django 5.1.2 on 2026-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Р В Р В РЎР РЋР РЏ Р В РЎвЂќР В Р’В»Р В РЎвЂР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Р В РЎвЂєР РЋРІР‚С™ 1 Р В РўвЂР В РЎвЂў 5', verbose_name='Р В РЎвЂєР РЋРІР‚В Р В Р’ВµР В Р вЂ¦Р В РЎвЂќР В Р’В°')),
                ('text', models.TextField(max_length=2000, verbose_name='Р В РЎС›Р В Р’ВµР В РЎвЂќР РЋР С“Р РЋРІР‚С™ Р В РЎвЂўР РЋРІР‚С™Р В Р’В·Р РЋРІР‚в„–Р В Р вЂ Р В Р’В°')),
                ('avatar', models.ImageField(blank=True, help_text='Р В РЎС™Р В Р’В°Р В РЎвЂќР РЋР С“Р В РЎвЂР В РЎР РЋРЎвЂњР В РЎ 5 Р В РЎС™Р В РІР‚, JPG/PNG', null=True, upload_to='reviews/avatars/%Y/%m/', verbose_name='Р В Р’В¤Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂў Р В Р’В°Р В Р вЂ Р В Р’В°Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР В Р’В°')),
                ('status', models.CharField(choices=[('pending', 'Р В РЎСљР В Р’В° Р В РЎР В РЎвЂўР В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°Р РЋРІР‚В Р В РЎвЂР В РЎвЂ'), ('approved', 'Р В РЎвЂєР В РўвЂР В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’ВµР В Р вЂ¦'), ('rejected', 'Р В РЎвЂєР РЋРІР‚С™Р В РЎвЂќР В Р’В»Р В РЎвЂўР В Р вЂ¦Р РЋРІР‚Р В Р вЂ¦')], db_index=True, default='pending', max_length=20, verbose_name='Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋРІР‚С™Р РЋРЎвЂњР РЋР С“')),
                ('is_verified', models.BooleanField(default=False, help_text='Р В РЎвЂєР РЋРІР‚С™Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В¶Р В Р’В°Р РЋРІР‚С™Р РЋР Р‰ Р В Р’В·Р В Р вЂ¦Р В Р’В°Р РЋРІР‚РЋР В РЎвЂўР В РЎвЂќ Р вЂ™Р’В«Р В РЎСџР РЋР вЂљР В РЎвЂўР В Р вЂ Р В Р’ВµР РЋР вЂљР В Р’ВµР В Р вЂ¦Р В РЎвЂўР вЂ™Р’В» Р РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎ Р РЋР С“ Р В РЎвЂР В РЎР В Р’ВµР В Р вЂ¦Р В Р’ВµР В РЎ', verbose_name='Р В РЎСџР РЋР вЂљР В РЎвЂўР В Р вЂ Р В Р’ВµР РЋР вЂљР В Р’ВµР В Р вЂ¦')),
                ('admin_comment', models.TextField(blank=True, help_text='Р В РІР‚в„ўР В Р вЂ¦Р РЋРЎвЂњР РЋРІР‚С™Р РЋР вЂљР В Р’ВµР В Р вЂ¦Р В Р вЂ¦Р В РЎвЂР В РІвЂћвЂ“ Р В РЎвЂќР В РЎвЂўР В РЎР В РЎР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР В РЎвЂР В РІвЂћвЂ“, Р В Р вЂ¦Р В Р’Вµ Р В РЎвЂ”Р В РЎвЂўР В РЎвЂќР В Р’В°Р В Р’В·Р РЋРІР‚в„–Р В Р вЂ Р В Р’В°Р В Р’ВµР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р вЂ¦Р В Р’В° Р РЋР С“Р В Р’В°Р В РІвЂћвЂ“Р РЋРІР‚С™Р В Р’Вµ', null=True, verbose_name='Р В РЎв„ўР В РЎвЂўР В РЎР В РЎР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР В РЎвЂР В РІвЂћвЂ“ Р В РЎР В РЎвЂўР В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°Р РЋРІР‚С™Р В РЎвЂўР РЋР вЂљР В Р’В°')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP Р В Р’В°Р В РўвЂР РЋР вЂљР В Р’ВµР РЋР С“ Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В РЎвЂР РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР РЏ', null=True, verbose_name='IP Р В Р’В°Р В РўвЂР РЋР вЂљР В Р’ВµР РЋР С“')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂ”Р РЋР вЂљР В Р’В°Р В Р вЂ Р В РЎвЂќР В РЎвЂ')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РЎР В РЎвЂўР В РўвЂР В Р’ВµР РЋР вЂљР В Р’В°Р РЋРІР‚В Р В РЎвЂР В РЎвЂ')),
            ],
            options={
                'verbose_name': 'Р В РЎвЂєР РЋРІР‚С™Р В Р’В·Р РЋРІР‚в„–Р В Р вЂ  Р В РЎвЂќР В Р’В»Р В РЎвЂР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°',
                'verbose_name_plural': 'Р В РЎвЂєР РЋРІР‚С™Р В Р’В·Р РЋРІР‚в„–Р В Р вЂ Р РЋРІР‚в„– Р В РЎвЂќР В Р’В»Р В РЎвЂР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В РЎвЂўР В Р вЂ ',
                'ordering': ['-created_at'],
            },
        ),
    ]
