# Generated by Django 5.1.2 on 2026-03-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Р В Р’В¤Р В Р В РЎвЂє')),
                ('phone', models.CharField(max_length=50, verbose_name='Р В РЎС›Р В Р’ВµР В Р’В»Р В Р’ВµР РЋРІР‚С›Р В РЎвЂўР В Р вЂ¦')),
                ('region', models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('FargР С™Р’В»ona viloyati', 'FargР С™Р’В»ona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('QoraqalpogР С™Р’В»iston Respublikasi', 'QoraqalpogР С™Р’В»iston Respublikasi')], max_length=100, verbose_name='Р В РІР‚СљР В РЎвЂўР РЋР вЂљР В РЎвЂўР В РўвЂ/Р В Р’В Р В Р’ВµР В РЎвЂ“Р В РЎвЂР В РЎвЂўР В Р вЂ¦')),
                ('preferred_date', models.DateField(verbose_name='Р В РІР‚вЂњР В Р’ВµР В Р’В»Р В Р’В°Р В Р’ВµР В РЎР В Р’В°Р РЋР РЏ Р В РўвЂР В Р’В°Р РЋРІР‚С™Р В Р’В°')),
                ('preferred_time', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00')], max_length=5, verbose_name='Р В РІР‚вЂњР В Р’ВµР В Р’В»Р В Р’В°Р В Р’ВµР В РЎР В РЎвЂўР В Р’Вµ Р В Р вЂ Р РЋР вЂљР В Р’ВµР В РЎР РЋР РЏ')),
                ('agree_terms', models.BooleanField(default=False, verbose_name='Р В Р Р‹Р В РЎвЂўР В РЎвЂ“Р В Р’В»Р В Р’В°Р РЋР С“Р В РЎвЂР В Р’Вµ Р В Р вЂ¦Р В Р’В° Р В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В±Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂќР РЋРЎвЂњ Р В РўвЂР В Р’В°Р В Р вЂ¦Р В Р вЂ¦Р РЋРІР‚в„–Р РЋРІР‚В¦')),
                ('status', models.CharField(choices=[('new', 'Р В РЎСљР В РЎвЂўР В Р вЂ Р В Р’В°Р РЋР РЏ'), ('confirmed', 'Р В РЎСџР В РЎвЂўР В РўвЂР РЋРІР‚С™Р В Р вЂ Р В Р’ВµР РЋР вЂљР В Р’В¶Р В РўвЂР В Р’ВµР В Р вЂ¦Р В Р’В°'), ('completed', 'Р В РІР‚вЂќР В Р’В°Р В Р вЂ Р В Р’ВµР РЋР вЂљР РЋРІвЂљВ¬Р В Р’ВµР В Р вЂ¦Р В Р’В°'), ('cancelled', 'Р В РЎвЂєР РЋРІР‚С™Р В РЎР В Р’ВµР В Р вЂ¦Р В Р’ВµР В Р вЂ¦Р В Р’В°')], db_index=True, default='new', max_length=20, verbose_name='Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋРІР‚С™Р РЋРЎвЂњР РЋР С“')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Р В РЎв„ўР В РЎвЂўР В РЎР В РЎР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР В РЎвЂР В РІвЂћвЂ“ Р В РЎР В Р’ВµР В Р вЂ¦Р В Р’ВµР В РўвЂР В Р’В¶Р В Р’ВµР РЋР вЂљР В Р’В°')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Р В Р’В°Р В РўвЂР РЋР вЂљР В Р’ВµР РЋР С“')),
                ('referer', models.URLField(blank=True, max_length=500, null=True, verbose_name='Referer')),
                ('utm_data', models.TextField(blank=True, null=True, verbose_name='UTM Р В РЎР В Р’ВµР РЋРІР‚С™Р В РЎвЂќР В РЎвЂ')),
                ('visitor_uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='amoCRM Visitor UID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р РЋР С“Р В РЎвЂўР В Р’В·Р В РўвЂР В Р’В°Р В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РЎвЂўР В Р’В±Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drive_requests', to='main.product', verbose_name='Р В РЎС™Р В РЎвЂўР В РўвЂР В Р’ВµР В Р’В»Р РЋР Р‰ Р В Р’В°Р В Р вЂ Р РЋРІР‚С™Р В РЎвЂўР В РЎР В РЎвЂўР В Р’В±Р В РЎвЂР В Р’В»Р РЋР РЏ')),
            ],
            options={
                'verbose_name': 'Р В РІР‚вЂќР В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В РЎвЂ - Р В РЎС›Р В Р’ВµР РЋР С“Р РЋРІР‚С™-Р В РўвЂР РЋР вЂљР В Р’В°Р В РІвЂћвЂ“Р В Р вЂ ',
                'verbose_name_plural': 'Р В РІР‚вЂќР В Р’В°Р РЋР РЏР В Р вЂ Р В РЎвЂќР В РЎвЂ - Р В РЎС›Р В Р’ВµР РЋР С“Р РЋРІР‚С™-Р В РўвЂР РЋР вЂљР В Р’В°Р В РІвЂћвЂ“Р В Р вЂ Р РЋРІР‚в„–',
                'ordering': ['-created_at'],
            },
        ),
    ]
