# Generated by Django 5.1.2 on 2026-03-16 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testdriverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdriverequest',
            name='region',
        ),
        migrations.AddField(
            model_name='testdriverequest',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drive_requests', to='main.dealer', verbose_name='Дилерский центр'),
        ),
    ]
