# Generated by Django 5.1.2 on 2026-03-16 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_testdriverequest_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(help_text='Например: Старший менеджер, Руководитель филиала', max_length=100, verbose_name='Должность')),
                ('position_uz', models.CharField(help_text='Например: Старший менеджер, Руководитель филиала', max_length=100, null=True, verbose_name='Должность')),
                ('position_ru', models.CharField(help_text='Например: Старший менеджер, Руководитель филиала', max_length=100, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(help_text='Например: Старший менеджер, Руководитель филиала', max_length=100, null=True, verbose_name='Должность')),
                ('photo', models.ImageField(help_text='Рекомендуемый размер: 400x400px, квадратное фото', upload_to='team/managers/%Y/', verbose_name='Фото')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='main.dealer', verbose_name='Филиал (дилерский центр)')),
            ],
            options={
                'verbose_name': 'Команда - Менеджер',
                'verbose_name_plural': 'Команда - Менеджеры филиалов',
                'ordering': ['dealer__order', 'order', 'full_name'],
            },
        ),
    ]
