# Generated by Django 5.2.6 on 2025-12-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contactform_referer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='referer',
            field=models.URLField(blank=True, help_text='URL страницы, с которой отправлена заявка', max_length=500, null=True, verbose_name='Referer (откуда пришёл)'),
        ),
    ]
