# Generated by Django 5.1.2 on 2026-03-16 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_testdriverequest_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Р В Р’В¤Р В Р В РЎвЂє')),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name='Р В Р’В¤Р В Р В РЎвЂє')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='Р В Р’В¤Р В Р В РЎвЂє')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='Р В Р’В¤Р В Р В РЎвЂє')),
                ('position', models.CharField(help_text='Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР РЋРІвЂљВ¬Р В РЎвЂР В РІвЂћвЂ“ Р В РЎР В Р’ВµР В Р вЂ¦Р В Р’ВµР В РўвЂР В Р’В¶Р В Р’ВµР РЋР вЂљ, Р В Р’В Р РЋРЎвЂњР В РЎвЂќР В РЎвЂўР В Р вЂ Р В РЎвЂўР В РўвЂР В РЎвЂР РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰ Р РЋРІР‚С›Р В РЎвЂР В Р’В»Р В РЎвЂР В Р’В°Р В Р’В»Р В Р’В°', max_length=100, verbose_name='Р В РІР‚СњР В РЎвЂўР В Р’В»Р В Р’В¶Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰')),
                ('position_uz', models.CharField(help_text='Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР РЋРІвЂљВ¬Р В РЎвЂР В РІвЂћвЂ“ Р В РЎР В Р’ВµР В Р вЂ¦Р В Р’ВµР В РўвЂР В Р’В¶Р В Р’ВµР РЋР вЂљ, Р В Р’В Р РЋРЎвЂњР В РЎвЂќР В РЎвЂўР В Р вЂ Р В РЎвЂўР В РўвЂР В РЎвЂР РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰ Р РЋРІР‚С›Р В РЎвЂР В Р’В»Р В РЎвЂР В Р’В°Р В Р’В»Р В Р’В°', max_length=100, null=True, verbose_name='Р В РІР‚СњР В РЎвЂўР В Р’В»Р В Р’В¶Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰')),
                ('position_ru', models.CharField(help_text='Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР РЋРІвЂљВ¬Р В РЎвЂР В РІвЂћвЂ“ Р В РЎР В Р’ВµР В Р вЂ¦Р В Р’ВµР В РўвЂР В Р’В¶Р В Р’ВµР РЋР вЂљ, Р В Р’В Р РЋРЎвЂњР В РЎвЂќР В РЎвЂўР В Р вЂ Р В РЎвЂўР В РўвЂР В РЎвЂР РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰ Р РЋРІР‚С›Р В РЎвЂР В Р’В»Р В РЎвЂР В Р’В°Р В Р’В»Р В Р’В°', max_length=100, null=True, verbose_name='Р В РІР‚СњР В РЎвЂўР В Р’В»Р В Р’В¶Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰')),
                ('position_en', models.CharField(help_text='Р В РЎСљР В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂР В РЎР В Р’ВµР РЋР вЂљ: Р В Р Р‹Р РЋРІР‚С™Р В Р’В°Р РЋР вЂљР РЋРІвЂљВ¬Р В РЎвЂР В РІвЂћвЂ“ Р В РЎР В Р’ВµР В Р вЂ¦Р В Р’ВµР В РўвЂР В Р’В¶Р В Р’ВµР РЋР вЂљ, Р В Р’В Р РЋРЎвЂњР В РЎвЂќР В РЎвЂўР В Р вЂ Р В РЎвЂўР В РўвЂР В РЎвЂР РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰ Р РЋРІР‚С›Р В РЎвЂР В Р’В»Р В РЎвЂР В Р’В°Р В Р’В»Р В Р’В°', max_length=100, null=True, verbose_name='Р В РІР‚СњР В РЎвЂўР В Р’В»Р В Р’В¶Р В Р вЂ¦Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР Р‰')),
                ('photo', models.ImageField(help_text='Р В Р’В Р В Р’ВµР В РЎвЂќР В РЎвЂўР В РЎР В Р’ВµР В Р вЂ¦Р В РўвЂР РЋРЎвЂњР В Р’ВµР В РЎР РЋРІР‚в„–Р В РІвЂћвЂ“ Р РЋР вЂљР В Р’В°Р В Р’В·Р В РЎР В Р’ВµР РЋР вЂљ: 400x400px, Р В РЎвЂќР В Р вЂ Р В Р’В°Р В РўвЂР РЋР вЂљР В Р’В°Р РЋРІР‚С™Р В Р вЂ¦Р В РЎвЂўР В Р’Вµ Р РЋРІР‚С›Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂў', upload_to='team/managers/%Y/', verbose_name='Р В Р’В¤Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂў')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Р В РЎС›Р В Р’ВµР В Р’В»Р В Р’ВµР РЋРІР‚С›Р В РЎвЂўР В Р вЂ¦')),
                ('is_active', models.BooleanField(default=True, verbose_name='Р В РЎвЂ™Р В РЎвЂќР РЋРІР‚С™Р В РЎвЂР В Р вЂ Р В Р’ВµР В Р вЂ¦')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Р В РЎСџР В РЎвЂўР РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎвЂќ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р В РІР‚СњР В Р’В°Р РЋРІР‚С™Р В Р’В° Р В РўвЂР В РЎвЂўР В Р’В±Р В Р’В°Р В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В РЎвЂР РЋР РЏ')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='main.dealer', verbose_name='Р В Р’В¤Р В РЎвЂР В Р’В»Р В РЎвЂР В Р’В°Р В Р’В» (Р В РўвЂР В РЎвЂР В Р’В»Р В Р’ВµР РЋР вЂљР РЋР С“Р В РЎвЂќР В РЎвЂР В РІвЂћвЂ“ Р РЋРІР‚В Р В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р РЋР вЂљ)')),
            ],
            options={
                'verbose_name': 'Р В РЎв„ўР В РЎвЂўР В РЎР В Р’В°Р В Р вЂ¦Р В РўвЂР В Р’В° - Р В РЎС™Р В Р’ВµР В Р вЂ¦Р В Р’ВµР В РўвЂР В Р’В¶Р В Р’ВµР РЋР вЂљ',
                'verbose_name_plural': 'Р В РЎв„ўР В РЎвЂўР В РЎР В Р’В°Р В Р вЂ¦Р В РўвЂР В Р’В° - Р В РЎС™Р В Р’ВµР В Р вЂ¦Р В Р’ВµР В РўвЂР В Р’В¶Р В Р’ВµР РЋР вЂљР РЋРІР‚в„– Р РЋРІР‚С›Р В РЎвЂР В Р’В»Р В РЎвЂР В Р’В°Р В Р’В»Р В РЎвЂўР В Р вЂ ',
                'ordering': ['dealer__order', 'order', 'full_name'],
            },
        ),
    ]
