# Generated by Django 5.2.6 on 2025-12-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_dashboard_alter_contactform_referer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('hero_image', models.ImageField(blank=True, help_text='Изображение для страницы категории', null=True, upload_to='categories/heroes/', verbose_name='Фоновое изображение')),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контент - Категория',
                'verbose_name_plural': 'Контент - Категории продуктов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='dealerrequirement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='services',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Контент - Автомобиль', 'verbose_name_plural': 'Контент - Автомобили'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='BecomeADealerApplication',
        ),
        migrations.DeleteModel(
            name='BecomeADealerPage',
        ),
        migrations.DeleteModel(
            name='DealerRequirement',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='DealerService',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Выберите одну или несколько категорий', related_name='products', to='main.productcategory', verbose_name='Категории'),
        ),
    ]
