# Generated by Django 5.1.2 on 2026-03-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_branchmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='description',
            field=models.TextField(blank=True, help_text="Diler markazi haqida qisqacha ma'lumot", verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='description_en',
            field=models.TextField(blank=True, help_text="Diler markazi haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='description_ru',
            field=models.TextField(blank=True, help_text="Diler markazi haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='description_uz',
            field=models.TextField(blank=True, help_text="Diler markazi haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif'),
        ),
        migrations.CreateModel(
            name='DealerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Salon rasmi. Tavsiya: 1200x800px', upload_to='dealers/gallery/%Y/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha')),
                ('caption_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha')),
                ('caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.dealer', verbose_name='Diler markazi')),
            ],
            options={
                'verbose_name': 'Diler rasmi',
                'verbose_name_plural': 'Diler rasmlari',
                'ordering': ['order'],
            },
        ),
    ]
