# Generated by Django 4.2.29 on 2026-03-30 07:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_dealer_description_dealer_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amocrmtoken',
            options={'verbose_name': 'amoCRM Токен', 'verbose_name_plural': 'amoCRM Токены'},
        ),
        migrations.AlterModelOptions(
            name='branchmanager',
            options={'ordering': ['dealer__order', 'order', 'full_name'], 'verbose_name': 'Команда - Менеджер', 'verbose_name_plural': 'Команда - Менеджеры филиалов'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявки - Общая заявка', 'verbose_name_plural': 'Заявки - Общие заявки'},
        ),
        migrations.AlterModelOptions(
            name='featureicon',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Контент - Иконка', 'verbose_name_plural': 'Контент - Иконки'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявки - Заявка на вакансию', 'verbose_name_plural': 'Заявки - Заявки на вакансии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-order', '-created_at'], 'verbose_name': ' - Новость', 'verbose_name_plural': 'Контент - Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsblock',
            options={'ordering': ['order'], 'verbose_name': 'Блок новости', 'verbose_name_plural': 'Блоки новостей'},
        ),
        migrations.AlterModelOptions(
            name='parametercategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Категория параметра', 'verbose_name_plural': 'Категории параметров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Контент - Автомобиль', 'verbose_name_plural': 'Контент - Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='productcardspec',
            options={'ordering': ['order'], 'verbose_name': 'Характеристика карточки', 'verbose_name_plural': 'Характеристики карточки'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Контент - Марка', 'verbose_name_plural': 'Контент - Марка автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'ordering': ['order'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики с иконками'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'ordering': ['order'], 'verbose_name': 'Фото галереи', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'ordering': ['category__order', 'order'], 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры машины'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв клиента', 'verbose_name_plural': 'Отзывы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='testdriverequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявки - Тест-драйв', 'verbose_name_plural': 'Заявки - Тест-драйвы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Вакансии - Вакансия', 'verbose_name_plural': 'Вакансии - Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='vacancycondition',
            options={'ordering': ['order'], 'verbose_name': 'Условие', 'verbose_name_plural': 'Условия'},
        ),
        migrations.AlterModelOptions(
            name='vacancyidealcandidate',
            options={'ordering': ['order'], 'verbose_name': 'Портрет кандидата', 'verbose_name_plural': 'Портрет кандидата'},
        ),
        migrations.AlterModelOptions(
            name='vacancyrequirement',
            options={'ordering': ['order'], 'verbose_name': 'Требование', 'verbose_name_plural': 'Требования'},
        ),
        migrations.AlterModelOptions(
            name='vacancyresponsibility',
            options={'ordering': ['order'], 'verbose_name': 'Обязанность', 'verbose_name_plural': 'Обязанности'},
        ),
        migrations.AlterField(
            model_name='amocrmtoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='amocrmtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='main.dealer', verbose_name='Филиал (дилерский центр)'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='photo',
            field=models.ImageField(help_text='Рекомендуемый размер: 400x400px, квадратное фото', upload_to='team/managers/%Y/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='position',
            field=models.CharField(help_text='Например: Старший менеджер, Руководитель филиала', max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='position_en',
            field=models.CharField(help_text='Например: Старший менеджер, Руководитель филиала', max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='position_ru',
            field=models.CharField(help_text='Например: Старший менеджер, Руководитель филиала', max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='position_uz',
            field=models.CharField(help_text='Например: Старший менеджер, Руководитель филиала', max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='amocrm_error',
            field=models.TextField(blank=True, help_text='Текст последней ошибки при отправке', null=True, verbose_name='Ошибка amoCRM'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='amocrm_lead_id',
            field=models.CharField(blank=True, help_text='ID лида после успешной отправки', max_length=50, null=True, verbose_name='ID лида в amoCRM'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='amocrm_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в amoCRM'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='amocrm_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Успешно отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='pending', help_text='Статус отправки в amoCRM', max_length=20, verbose_name='Статус amoCRM'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uz_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='product',
            field=models.CharField(blank=True, help_text='Какую модель автомобиля интересует клиента', max_length=200, null=True, verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='referer',
            field=models.URLField(blank=True, help_text='URL страницы, с которой отправлена заявка', max_length=500, null=True, verbose_name='Referer (откуда пришёл)'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='region',
            field=models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Fargʻona viloyati', 'Fargʻona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Qoraqalpogʻiston Respublikasi', 'Qoraqalpogʻiston Respublikasi')], max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('done', 'Обработана')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='utm_data',
            field=models.TextField(blank=True, help_text='UTM метки в JSON формате', null=True, verbose_name='UTM метки'),
        ),
        migrations.AlterField(
            model_name='featureicon',
            name='icon',
            field=models.FileField(upload_to='features/icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='featureicon',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='featureicon',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий HR'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Рассмотрено'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='region',
            field=models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Fargʻona viloyati', 'Fargʻona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Qoraqalpogʻiston Respublikasi', 'Qoraqalpogʻiston Respublikasi')], max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Фото автора'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(help_text='Введите дату публикации вручную', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(help_text='Отображается в превью новости', max_length=200, verbose_name='Краткое описание для карточки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_en',
            field=models.TextField(help_text='Отображается в превью новости', max_length=200, null=True, verbose_name='Краткое описание для карточки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_ru',
            field=models.TextField(help_text='Отображается в превью новости', max_length=200, null=True, verbose_name='Краткое описание для карточки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_uz',
            field=models.TextField(help_text='Отображается в превью новости', max_length=200, null=True, verbose_name='Краткое описание для карточки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показывать новость на сайте', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем больше число, тем выше в списке', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/previews/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Генерируется автоматически из заголовка', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('youtube', 'YouTube видео'), ('video', 'Видео файл')], max_length=10, verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.news', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок H3 перед текстовым блоком', max_length=500, null=True, verbose_name='Заголовок (необязательно)'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='title_en',
            field=models.CharField(blank=True, help_text='Заголовок H3 перед текстовым блоком', max_length=500, null=True, verbose_name='Заголовок (необязательно)'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Заголовок H3 перед текстовым блоком', max_length=500, null=True, verbose_name='Заголовок (необязательно)'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Заголовок H3 перед текстовым блоком', max_length=500, null=True, verbose_name='Заголовок (необязательно)'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='news/videos/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube ссылка'),
        ),
        migrations.AlterField(
            model_name='parametercategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='parametercategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='parametercategory',
            name='slug',
            field=models.SlugField(help_text='«Например: двигатель, вес, кабина. Только латинские буквы и тире».', max_length=100, unique=True, verbose_name='«Слуг (кодекс)»'),
        ),
        migrations.AlterField(
            model_name='product',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/cards/', verbose_name='Изображение для карточки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию автомобиля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Продукт будет добавлен в главный слайдер', verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/main/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_fuel_consumption',
            field=models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_fuel_consumption_en',
            field=models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_fuel_consumption_ru',
            field=models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_fuel_consumption_uz',
            field=models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 420x210px. Если не указано, используется main_image', null=True, upload_to='products/slider/', verbose_name='Изображение для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем больше число, тем раньше появится в слайдере', verbose_name='Порядок в слайдере'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_power',
            field=models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_power_en',
            field=models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_power_ru',
            field=models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_power_uz',
            field=models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_price',
            field=models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_price_en',
            field=models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_price_ru',
            field=models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_price_uz',
            field=models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider_year',
            field=models.CharField(default='2025', help_text='Отображается в слайдере', max_length=4, verbose_name='Год для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='productcardspec',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productcardspec',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productcardspec',
            name='value_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productcardspec',
            name='value_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productcardspec',
            name='value_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Изображение для страницы категории', null=True, upload_to='categories/heroes/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='main.parametercategory', verbose_name='Категория параметра'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='main.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='text_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='review',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Внутренний комментарий, не показывается на сайте', null=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Максимум 5 МБ, JPG/PNG', null=True, upload_to='reviews/avatars/%Y/%m/', verbose_name='Фото аватара'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP адрес отправителя', null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Отображать значок «Проверено» рядом с именем', verbose_name='Проверен'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='От 1 до 5', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='agree_terms',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drive_requests', to='main.dealer', verbose_name='Дилерский центр'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='preferred_date',
            field=models.DateField(verbose_name='Желаемая дата'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='preferred_time',
            field=models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00')], max_length=5, verbose_name='Желаемое время'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drive_requests', to='main.product', verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='testdriverequest',
            name='utm_data',
            field=models.TextField(blank=True, null=True, verbose_name='UTM метки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_info',
            field=models.TextField(default='Присылайте резюме на info@autoliga.uz', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_info_en',
            field=models.TextField(default='Присылайте резюме на info@autoliga.uz', null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_info_ru',
            field=models.TextField(default='Присылайте резюме на info@autoliga.uz', null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_info_uz',
            field=models.TextField(default='Присылайте резюме на info@autoliga.uz', null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description_uz',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='vacancycondition',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='vacancycondition',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='vacancycondition',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='vacancycondition',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='vacancycondition',
            name='text_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='vacancyidealcandidate',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='vacancyidealcandidate',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='vacancyidealcandidate',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='vacancyidealcandidate',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='vacancyidealcandidate',
            name='text_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='vacancyrequirement',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='vacancyrequirement',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Требование'),
        ),
        migrations.AlterField(
            model_name='vacancyrequirement',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Требование'),
        ),
        migrations.AlterField(
            model_name='vacancyrequirement',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Требование'),
        ),
        migrations.AlterField(
            model_name='vacancyrequirement',
            name='text_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Требование'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='vacancyresponsibility',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
