# Generated by Django 5.2.6 on 2025-12-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productcategory_remove_dealerrequirement_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Контент - Марка', 'verbose_name_plural': 'Контент - Марка автомобиля'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию автомобиля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productcategory', verbose_name='Категория'),
        ),
    ]
