# Generated by Django 4.2.29 on 2026-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_amocrmtoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=20, verbose_name='Status'),
        ),
    ]
