# Generated by Django 4.2.29 on 2026-04-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_telegramuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='status',
        ),
    ]
